version: '3'

services:
  sambot:
    container_name: sambot
    build:
        context: .
    ports:
      - 3000:3000
    volumes:
      - logs:/code/logs/
    environment:
      - TEST_MODE=1
volumes:
  logs:
